### ISSUE TITLE
Events missing from snapshots

### ISSUE THREAD

**Issue by Vaakapallo** [testmycode/tmc-netbeans#108]
Submission events (and at least one whole exercise) are missing from the snapshots, but can be seen on the TMC-site.

It might something to do with closing down Netbeans. A lot of the missing data seems the occur at the same time as students finish coding for the day. So the submission events are missing from the last exercise in a coding session.

So it might be that when NetBeans closes, data gathered after the last save is lost. Or the save buffer runs out of space and stops saving events.

**Comment by jamox** [comment]
Closed in 6f7ee0194b29e0eb93e223ccb66b091fab983973
