### ISSUE TITLE
Bug in showing Settings

### ISSUE THREAD

**Issue by UMTti** [testmycode/tmc-netbeans#109]
1. Start NetBeans
2. Click TMC -> Settings
3. Click closing cross
4. Click TMC -> Settings 
-----> Settings panel doesn't open 

Issue is located in https://github.com/testmycode/tmc-netbeans/blob/master/tmc-plugin/src/fi/helsinki/cs/tmc/actions/ShowSettingsAction.java#L46 , the program thinks that prefUiFactory.isPreferencesUiVisible() is true and returns from function which shows preferences panel. This happens, because dialog is created in step 2, but it isn't destroyed correctly then. 

DialogDescriptor is created in https://github.com/testmycode/tmc-netbeans/blob/master/tmc-plugin/src/fi/helsinki/cs/tmc/ui/PreferencesUIFactory.java#L89. In constructor there is                 NotifyDescriptor.OK_CANCEL_OPTION, but nothing related to closing option. 

We tried to add descriptor.setClosingOptions(new Object[]{NotifyDescriptor.CLOSED_OPTION}); after constructor but it didn't help.

**Comment by a544jh** [comment]
I could take a look at this

**Comment by a544jh** [comment]
This is now fixed & merged

**Comment by jamox** [comment]
Oh right, I was hoping on github to automatically close this...
