### ISSUE TITLE
Refactor long methods in TMC-plugin's actions

### ISSUE THREAD

**Issue by Mession** [testmycode/tmc-netbeans#110]
[See here](https://github.com/testmycode/tmc-netbeans/blob/core_integration/tmc-plugin/src/fi/helsinki/cs/tmc/actions/)

Problematic files:
CheckForNewExercisesOrUpdates.java
CheckForNewReviews.java
DownloadCompletedExercises.java
RefreshCoursesAction.java
RequestReviewAction.java
ReviewEventListener.java
SaveSettingsAction.java
ShowSettingsAction.java
TmcModuleInstall.java

**Comment by Mession** [comment]
There's a similar problem [here](https://github.com/testmycode/tmc-netbeans/blob/core_integration/tmc-plugin/src/fi/helsinki/cs/tmc/exerciseSubmitter/ExerciseSubmitter.java).

**Comment by hzhulkko** [comment]
I'd like to work on this one.

**Comment by jamox** [comment]
Let's close this as most of the code of tmc-netbeans plugin will be removed while we migrate to use tmc-core
