### ISSUE TITLE
Fail to log to TMC : incorrect username or password

### ISSUE THREAD

**Issue by Hyponeros** [testmycode/tmc-netbeans#135]
Hello,
I have been using tmc-netbeans for 2 months.
Once, I lost my TMC account informations. Then I created a new account but was never able to reconnect to TMC : "incorrect username or password"

I tried to uninstall/install tmc-netbeans and had the same problem the IntelliJ IDEA.

Any sort of advise would be appreciated.
Thank you.

**Comment by nygrenh** [comment]
If you're using one of the mooc.fi servers (which likely is the case), send a message to `mooc@cs.helsinki.fi`

**Comment by Hyponeros** [comment]
Thank you. I will.
