### ISSUE TITLE
TMC keeps opening Internet Explorer on Windows 10, despite Netbeans 8.2 settings pointing to Chrome/Firefox, works fine outside TMC

### ISSUE THREAD

**Issue by Snorkeldink** [testmycode/tmc-netbeans#144]
OS: Windows 10
IDE: Netbeans 8.2 
JDK: 8u141 x64
TMC : 1.1.7

TMC keeps opening Internet Explorer (when setting up) and when submitting (the solution link) or when going to TMC pastebin. It ignores default system settings and ignores netbeans 8.2 settings (to chrome or firefox).

If internet explorer 11 is not installed / removed, then it will return an error that the external broswer is unavailable. 

I suspect the issue is in the "org.openide.awt.HtmlBrowser" library ? more specifically the "HtmlBrowser.URLDisplayer.getDefault()" is probably not returning the correct result ? (sorry I'm new and learning ...)

It's just very annoying that it always want to open internet explorer for some reason.

**Comment by Snorkeldink** [comment]
Tested on multiple Windows 10 clients ... same issue everywhere. Easy to reproduce on any Windows 10 machine.

**Comment by nigoshh** [comment]
I confirm that I have the same problem on my Windows 10 machine.

OS: Windows 10
IDE: Netbeans 8.2
TMC : 1.1.8

**Comment by nygrenh** [comment]
As of NetBeans with TMC 1.2.2, it should now respect the system's default browser.
