### ISSUE TITLE
Excercise feedback window takes multiple seconds to load

### ISSUE THREAD

**Issue by ljleppan** [testmycode/tmc-netbeans#149]
The exercise feedback window (shown after all tests pass on server) takes multiple seconds to load on a high-end PC running Windows 10. During the loading, the system is completely unresponsive.

The window seems to load to a stage where only the yellow smiley is missing, then hang for a few seconds, displays the smiley and then works fine.

Not a huge issue, but makes the program annoying to use.

**Comment by nygrenh** [comment]
This is a duplicate licate of #148

**Comment by ljleppan** [comment]
Thanks, closing this as a duplicate.
