### ISSUE TITLE
support maven project type

### ISSUE THREAD

**Issue by homberghp** [testmycode/tmc-netbeans#150]
Although ant has still the best experience for novices, maven is probably the way to go.
Would like to see maven projects as first-class citizens in this pugin, so that the exercise projects
can be distributed without tons of jars to make up the dependecies.

**Comment by nygrenh** [comment]
We already have support for Maven. You can find example exercises here: https://github.com/testmycode/tmc-testcourse. Our only limitation is that maven dependencies must be cached on our sandbox beforehand as there is no internet access.
